### ISSUE TITLE
SIGKILL from Python Signal library not available on Windows

### ISSUE THREAD

**Issue by Craig-ling** [jrwdunham/old-pyramid#38]
#37 
Python 3.6 on Windows
make create-old-instance OLD_NAME=myold
results in
"ImportError: cannot import name SIGKILL"

https://docs.python.org/3/library/signal.html
>     signal.SIGKILL
>     Kill signal.
>     It cannot be caught, blocked, or ignored.
>     Availability: Unix.

modified parser.py to only call SIGKILL on non-windows OS.

**Comment by jrwdunham** [comment]
Should be resolved by merging of https://github.com/dativebase/old-pyramid/pull/37
